name: Release Drafter

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your Next Release Notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@67e173cadb2fbd3de94f4a861e0c48c913b462ae # v6.4.0
        with:
          # Default: false
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
